server:
  port: 8095
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-goods-feign
eureka:
  client:
    service-url:
      # eureka server的通讯地址，注意路径
      defaultZone: http://127.0.0.1:8761/eureka/
      #defaultZone: http://eurekaService1:8761/eureka/,http://eurekaService2:8762/eureka/
  instance:
    # 是否将IP注册到eureka server，false：否，ture：是
    prefer-ip-address: true